### PR TITLE
Support extra records in _amazonses for multiple accounts

### PR DESCRIPTION
**Pull request by mbarrien**
Adds support for having multiple _amazonses verification records. Since a single domain might be used as the outbound mail domain in SES in multiple AWS accounts, each AWS account may have its own unique verification value that needs to be injected in the TXT record for _amazonses.${domain}. Route 53 disallows having multiple TXT records for the same name, so you have to put them all in one record.

This PR allows a user to inject their own values into the TXT record, which they either have to manually obtain themselves or as read from another Terraform module/resource. This is in addition to the one created specifically by this module for this account. Backwards compatibility is achieved by defaulting to an empty list.

### CODE REVIEW

**Comment by mdawn** [comment]
@mbarrien Do you happen to have a [Terratest](https://github.com/gruntwork-io/terratest) for this situation? If not, mind if I push one to your branch?

**Comment by mbarrien** [comment]
No terratest written; feel free to push one.

**Comment by mdawn** [comment]
Test is good to go but I'm not [allowed to push to your branch](https://docs.github.com/en/enterprise/2.13/user/articles/enabling-branch-restrictions). 🤕

**Comment by mbarrien** [comment]
@mdawn I don't see the normal option to be able to allow maintainers to push to my branch. I cannot let you push to the branch via Github permissions unless I add you to the org, which I cannot do. I don't see your fork/branch, so I can't cherry pick your change in. Do you have a public place you've pushed your tests into so that I can merge/cherry-pick your change into my branch?

**Comment by mdawn** [comment]
I see. Let's do this: Just pull in master & get it mergeable.
I'll approve the PR and then add the tests after.

**Comment by mbarrien** [comment]
Merged master branch into this. Ready for merge.

**Comment by mdawn** [comment]
Stall on terratest job in circleci. Merging as admin.

**Pull request merged**
